some docs
dfint/df-steam-hook-rs pull request #30
Opened 2023-11-27 18:59 UTC by BASM

2023-11-27 19:00 UTC, BASM commented
More info about prepare, build and run DF

2023-11-27 19:06 UTC, insolor requested changes

2023-11-27 19:06 UTC, insolor commented on README.md
> +#### lanch
Launch

2023-11-27 19:06 UTC, insolor commented on README.md
> +```
or `Dwarf Fortress.exe`, windows version is supported too

2023-11-27 19:06 UTC, insolor commented on README.md
> +#### build
In general, it's better to make the first letter of a header capital, and don't use h4 and smaller headers.

2023-11-28 06:38 UTC, BASM commented
I wrote that the build&launch is the same for Windows. Unfortunately, I am unable to test the instructions on Windows, so I cannot correct them for that operating system. I suspect that the name of the executable file is not the only one difference.

2023-11-28 06:48 UTC, insolor commented
@BASM building process on Windows is more or less the same, just the name of the library is dfint_hook.dll instead of libdfint_hook.so. See build workflow: https://github.com/dfint/df-steam-hook-rs/blob/main/.github/workflows/build.yml

2023-11-28 06:58 UTC, shevernitskiy commented
That is right, the same cli command, output as dll.

2023-11-28 16:44 UTC, insolor approved these changes

2023-11-28 16:48 UTC, merged